image: Visual Studio 2022
version: 1.0.{build}
configuration: Release

dotnet_csproj:
  patch: true
  file: 'src\PrivateGalleryCreator.csproj'
  version: '{version}'

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore src\PrivateGalleryCreator.csproj --verbosity m

build_script:
  - cmd: dotnet publish src\PrivateGalleryCreator.csproj

artifacts:
  - path: 'src\bin\$(configuration)\net6.0\publish'
    name: PrivateGalleryCreator
